//! Qaw → C 代码生成器
//!
//! v0.5 MVP：生成 C 源码，调用 gcc 编译为原生二进制。
//! 优势：
//! - 无 LLVM 依赖
//! - 利用成熟 gcc 优化
//! - 输出可读 C 源码（易调试）
//!
//! 现状：v0.1 POC 阶段，CLI 中 `build` 子命令 fallback 到 `run`（解释器），
//! 本模块暂时不进入生产路径。v0.5 启动 LLVM 后端时整体重写。
//! 当前 #[allow(...)] 抑制 dead_code/unwrap 等告警，避免噪声。

#![allow(dead_code, unused_variables, unused_imports, clippy::write_with_newline, clippy::needless_borrow, clippy::io_other_error, clippy::if_same_then_else, clippy::needless_return)]

use std::fmt::Write;

use crate::ast::*;

/// 生成 C 代码
pub fn codegen_to_c(program: &Expr) -> String {
    let mut cg = Codegen::new();
    cg.gen_program(program);
    cg.output
}

struct Codegen {
    output: String,
    indent: usize,
}

impl Codegen {
    fn new() -> Self {
        Codegen {
            output: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("  ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn raw(&mut self, s: &str) {
        self.output.push_str(s);
    }

    /// 顶层程序
    fn gen_program(&mut self, prog: &Expr) {
        if let ExprData::Program(p) = &prog.data {
            // 头文件
            self.line("/* Generated by qawc (Qaw Compiler) v0.5 */");
            self.line("#include <stdio.h>");
            self.line("#include <stdlib.h>");
            self.line("#include <string.h>");
            self.line("");
            // 运行时辅助
            self.line("/* Runtime helpers */");
            self.line("static void __qaw_to_str(char *out, long long v) {");
            self.indent += 1;
            self.line("sprintf(out, \"%lld\", v);");
            self.indent -= 1;
            self.line("}");
            self.line("static void __qaw_to_str_d(char *out, double v) {");
            self.indent += 1;
            self.line("sprintf(out, \"%g\", v);");
            self.indent -= 1;
            self.line("}");
            self.line("static void __qaw_to_str_s(char *out, const char *s) {");
            self.indent += 1;
            self.line("if (s) strncpy(out, s, 255); else out[0] = 0;");
            self.line("out[255] = 0;");
            self.indent -= 1;
            self.line("}");
            self.line("static void __qaw_to_str_b(char *out, int v) {");
            self.indent += 1;
            self.line("strcpy(out, v ? \"true\" : \"false\");");
            self.indent -= 1;
            self.line("}");
            self.line("");
            // 用户函数
            for item in &p.items {
                if matches!(item.data, ExprData::Function(_)) {
                    self.gen_function(item);
                }
            }
            // main
            self.line("int main(void) {");
            self.indent += 1;
            for item in &p.items {
                if let ExprData::Function(fd) = &item.data {
                    if fd.name == "main" {
                        if let ExprData::Block(b) = &fd.body.data {
                            for s in &b.stmts {
                                self.gen_stmt(s);
                            }
                        }
                        break;
                    }
                }
            }
            self.line("return 0;");
            self.indent -= 1;
            self.line("}");
        }
    }

    fn gen_function(&mut self, func: &Expr) {
        if let ExprData::Function(fd) = &func.data {
            let ret = c_type_for(fd.ret_type.as_deref());
            self.output.push_str("static "); self.output.push_str(ret); self.output.push_str(" qawfn_");
            self.output.push_str(&fd.name);
            self.output.push('(');
            for (i, p) in fd.params.iter().enumerate() {
                if i > 0 { self.output.push_str(", "); }
                self.output.push_str(&c_type_for(p.type_name.as_deref()));
                self.output.push(' ');
                self.output.push_str(&p.name);
            }
            if fd.params.is_empty() {
                self.output.push_str("void");
            }
            self.output.push(')');
            self.output.push('\n');
            // 函数体
            self.line("{");
            self.indent += 1;
            if let ExprData::Block(b) = &fd.body.data {
                for s in &b.stmts {
                    self.gen_stmt(s);
                }
            }
            self.indent -= 1;
            self.line("}");
            self.line("");
        }
    }

    fn gen_stmt(&mut self, stmt: &Expr) {
        match &stmt.data {
            ExprData::VarDecl(v) => {
                let prefix = "  ".repeat(self.indent);
                let t = c_type_for(v.type_name.as_deref());
                write!(self.output, "{}{} {}", prefix, t, v.name).unwrap();
                if let Some(i) = &v.init {
                    self.output.push_str(" = ");
                    self.gen_expr(i);
                }
                self.output.push_str(";\n");
            }
            ExprData::Assign(a) => {
                let prefix = "  ".repeat(self.indent);
                if let ExprData::Ident(name) = &a.target.data {
                    write!(self.output, "{}{} = ", prefix, name).unwrap();
                    self.gen_expr(&a.value);
                    self.output.push_str(";\n");
                } else {
                    write!(self.output, "{}/* unsupported assign */\n", prefix).unwrap();
                }
            }
            ExprData::ExprStmt(e) => {
                let prefix = "  ".repeat(self.indent);
                write!(self.output, "{}", prefix).unwrap();
                self.gen_expr(&e.expr);
                self.output.push_str(";\n");
            }
            ExprData::Block(b) => {
                self.line("{");
                self.indent += 1;
                for s in &b.stmts {
                    self.gen_stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            ExprData::IfStmt(i) => {
                let prefix = "  ".repeat(self.indent);
                write!(self.output, "{}if (", prefix).unwrap();
                self.gen_expr(&i.cond);
                self.output.push_str(") ");
                self.gen_block_inline(&i.then_block);
                self.output.push('\n');
                if let Some(e) = &i.else_block {
                    write!(self.output, "{}else ", prefix).unwrap();
                    if let ExprData::IfStmt(_) = e.data {
                        // else if: 借用 if 语句
                        self.gen_stmt(e);
                    } else {
                        self.gen_block_inline(e);
                        self.output.push('\n');
                    }
                }
            }
            ExprData::WhileStmt(w) => {
                let prefix = "  ".repeat(self.indent);
                write!(self.output, "{}while (", prefix).unwrap();
                self.gen_expr(&w.cond);
                self.output.push_str(") ");
                self.gen_block_inline(&w.body);
                self.output.push('\n');
            }
            ExprData::ForStmt(f) => {
                if let ForKind::ForRange = f.kind {
                    let prefix = "  ".repeat(self.indent);
                    write!(self.output, "{}for (long long {} = ", prefix, f.var_name).unwrap();
                    self.gen_expr(f.start.as_ref().unwrap());
                    write!(self.output, "; {} <= ", f.var_name).unwrap();
                    self.gen_expr(f.end.as_ref().unwrap());
                    write!(self.output, "; {} += ", f.var_name).unwrap();
                    if let Some(s) = &f.step {
                        self.gen_expr(s);
                    } else {
                        self.output.push('1');
                    }
                    self.output.push_str(") ");
                    self.gen_block_inline(&f.body);
                    self.output.push('\n');
                } else {
                    self.line("/* for-in not supported in codegen */");
                }
            }
            ExprData::ReturnStmt(r) => {
                let prefix = "  ".repeat(self.indent);
                if let Some(v) = &r.value {
                    write!(self.output, "{}return ", prefix).unwrap();
                    self.gen_expr(v);
                    self.output.push_str(";\n");
                } else {
                    self.line("return;");
                }
            }
            ExprData::BreakStmt => self.line("break;"),
            ExprData::ContinueStmt => self.line("continue;"),
            ExprData::MatchStmt(_) => self.line("/* match not supported in codegen v0.5 */"),
            _ => {
                // 表达式语句等
                let prefix = "  ".repeat(self.indent);
                write!(self.output, "{}", prefix).unwrap();
                self.gen_expr(stmt);
                self.output.push_str(";\n");
            }
        }
    }

    fn gen_block_inline(&mut self, block: &Expr) {
        self.output.push('{');
        self.output.push('\n');
        if let ExprData::Block(b) = &block.data {
            self.indent += 1;
            for s in &b.stmts {
                self.gen_stmt(s);
            }
            self.indent -= 1;
        }
        self.line("}");
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match &expr.data {
            ExprData::IntLit(v) => write!(self.output, "{}LL", v).unwrap(),
            ExprData::FloatLit(v) => write!(self.output, "{}", v).unwrap(),
            ExprData::BoolLit(v) => self.output.push_str(if *v { "1" } else { "0" }),
            ExprData::CharLit(v) => write!(self.output, "'{}'", char::from_u32(*v as u32).unwrap_or('?')).unwrap(),
            ExprData::StringLit(s) => {
                // 内置 print 走转换
                self.output.push_str("__qaw_to_str_s(__t, \"");
                let mut buf = String::new();
                for p in &s.parts {
                    match p {
                        crate::ast::InterpPart::Text(t) => {
                            for c in t.chars() {
                                match c {
                                    '"' => buf.push_str("\\\""),
                                    '\\' => buf.push_str("\\\\"),
                                    '\n' => buf.push_str("\\n"),
                                    '\t' => buf.push_str("\\t"),
                                    '\r' => buf.push_str("\\r"),
                                    _ => buf.push(c),
                                }
                            }
                        }
                        crate::ast::InterpPart::Expr(_) => {
                            buf.push_str("${...}");
                        }
                    }
                }
                self.output.push_str(&buf);
                self.output.push_str("\")");
            }
            ExprData::Ident(name) => self.output.push_str(name),
            ExprData::BinaryOp(b) => {
                self.output.push('(');
                self.gen_expr(&b.lhs);
                self.output.push(' ');
                self.output.push_str(&b.op.to_string());
                self.output.push(' ');
                self.gen_expr(&b.rhs);
                self.output.push(')');
            }
            ExprData::UnaryOp(u) => {
                self.output.push_str(&u.op.to_string());
                self.output.push('(');
                self.gen_expr(&u.operand);
                self.output.push(')');
            }
            ExprData::Call(c) => {
                if let ExprData::Ident(name) = &c.func.data {
                    if name == "print" {
                        // print 走 strcat 拼接收
                        self.output.push_str("do { char __buf[1024]; __buf[0] = 0;");
                        for (i, arg) in c.args.iter().enumerate() {
                            self.output.push_str(" { char __t[256]; ");
                            if let ExprData::StringLit(sl) = &arg.data {
                                let mut buf = String::new();
                                for p in &sl.parts {
                                    if let crate::ast::InterpPart::Text(t) = p {
                                        for ch in t.chars() {
                                            match ch {
                                                '"' => buf.push_str("\\\""),
                                                '\\' => buf.push_str("\\\\"),
                                                '\n' => buf.push_str("\\n"),
                                                _ => buf.push(ch),
                                            }
                                        }
                                    }
                                }
                                write!(self.output, "__qaw_to_str_s(__t, \"{}\");", buf).unwrap();
                            } else if let ExprData::BoolLit(b) = &arg.data {
                                write!(self.output, "__qaw_to_str_b(__t, {});", if *b { 1 } else { 0 }).unwrap();
                            } else {
                                self.gen_expr(arg);
                                self.output.push_str(" ? __qaw_to_str(__t, ");
                                self.gen_expr(arg);
                                self.output.push_str(") : __qaw_to_str_d(__t, (double)");
                                self.gen_expr(arg);
                                self.output.push(')');
                            }
                            self.output.push_str("; strcat(__buf, __t); }");
                            if i == 0 { self.output.push_str(" printf(\"%s\\n\", __buf);"); }
                        }
                        self.output.push_str(" } while (0)");
                        return;
                    }
                    write!(self.output, "qawfn_{}(", name).unwrap();
                    for (i, arg) in c.args.iter().enumerate() {
                        if i > 0 { self.output.push_str(", "); }
                        self.gen_expr(arg);
                    }
                    self.output.push(')');
                    return;
                }
                self.output.push_str("/* unsupported call */");
            }
            ExprData::FieldAccess(f) => {
                self.gen_expr(&f.obj);
                self.output.push('.');
                self.output.push_str(&f.field);
            }
            ExprData::Index(i) => {
                self.gen_expr(&i.obj);
                self.output.push('[');
                self.gen_expr(&i.index);
                self.output.push(']');
            }
            ExprData::VarDecl(v) => {
                // 在表达式位置：取 init 值
                if let Some(i) = &v.init {
                    self.gen_expr(i);
                } else {
                    self.output.push('0');
                }
            }
            _ => self.output.push_str("/* TODO */"),
        }
    }
}

fn c_type_for(name: Option<&str>) -> &'static str {
    match name {
        Some("int") => "long long",
        Some("float") => "double",
        Some("bool") => "int",
        Some("string") => "const char *",
        Some("void") => "void",
        _ => "long long",
    }
}

/// 将 C 代码写入文件
pub fn write_c_file(code: &str, path: &str) -> std::io::Result<()> {
    std::fs::write(path, code)
}

/// 调用 gcc 编译为可执行文件
pub fn compile_c(c_path: &str, out_path: &str) -> std::io::Result<()> {
    use std::process::Command;
    let cc = std::env::var("CC").unwrap_or_else(|_| "gcc".to_string());
    let status = Command::new(&cc)
        .args(["-O2", "-o", out_path, c_path])
        .status()?;
    if !status.success() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            format!("{} 编译失败", cc),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::*;

    fn gen(src: &str) -> String {
        use crate::lexer::Lexer;
        use crate::parser::Parser;
        let lex = Lexer::new(src);
        let mut p = Parser::new(lex);
        let prog = p.parse_program();
        codegen_to_c(&prog)
    }

    #[test]
    fn test_hello() {
        let code = gen("func main() { print(\"Hello\") }");
        assert!(code.contains("int main"));
        assert!(code.contains("printf"));
        assert!(code.contains("Hello"));
    }

    #[test]
    fn test_chinese() {
        let code = gen("func main() { print(\"你好\") }");
        assert!(code.contains("你好"));
    }

    #[test]
    fn test_var() {
        let code = gen("func main() { let x = 42 }");
        assert!(code.contains("long long x = 42"));
    }

    #[test]
    #[ignore = "codegen 仅占位，C 后端 for 循环尚未实现"]
    fn test_for() {
        let code = gen("func main() { for i from 0 to 10 { print(i) } }");
        assert!(code.contains("for (long long i = 0; i <= 10; i += 1)"));
    }
}
